<?php

return [
    'countries' => [
        ['AE', 'United Arab Emirates'],
        ['AF', 'Afghanistan'],
        ['AL', 'Albania'],
        ['AM', 'Armenia'],
        ['AO', 'Angola'],
        ['AR', 'Argentina'],
        ['AU', 'Australia'],
        ['AW', 'Aruba'],
        ['AZ', 'Azerbaijan'],
        ['BA', 'Bosnia and Herzegovina'],
        ['BB', 'Barbados'],
        ['BD', 'Bangladesh'],
        ['BG', 'Bulgaria'],
        ['BH', 'Bahrain'],
        ['BI', 'Burundi'],
        ['BM', 'Bermuda'],
        ['BN', 'Brunei'],
        ['BO', 'Bolivia'],
        ['BR', 'Brazil'],
        ['BS', 'Bahamas'],
        ['BT', 'Bhutan'],
        ['BW', 'Botswana'],
        ['BY', 'Belarus'],
        ['BZ', 'Belize'],
        ['CA', 'Canada'],
        ['CD', 'Democratic Republic of the Congo'],
        ['CH', 'Switzerland'],
        ['CL', 'Chile'],
        ['CN', 'China'],
        ['CO', 'Colombia'],
        ['CR', 'Costa Rica'],
        ['CU', 'Cuba'],
        ['CV', 'Cape Verde'],
        ['CZ', 'Czech Republic'],
        ['DE', 'Germany'],
        ['DJ', 'Djibouti'],
        ['DK', 'Denmark'],
        ['DO', 'Dominican Republic'],
        ['DZ', 'Algeria'],
        ['EG', 'Egypt'],
        ['ER', 'Eritrea'],
        ['ES', 'Spain'],
        ['ET', 'Ethiopia'],
        ['FI', 'Finland'],
        ['FJ', 'Fiji'],
        ['FK', 'Falkland Islands'],
        ['FO', 'Faroe Islands'],
        ['FR', 'France'],
        ['GB', 'United Kingdom'],
        ['GE', 'Georgia'],
        ['GG', 'Guernsey'],
        ['GH', 'Ghana'],
        ['GI', 'Gibraltar'],
        ['GM', 'The Gambia'],
        ['GN', 'Guinea'],
        ['GT', 'Guatemala'],
        ['GY', 'Guyana'],
        ['HK', 'Hong Kong'],
        ['HN', 'Honduras'],
        ['HR', 'Croatia'],
        ['HT', 'Haiti'],
        ['HU', 'Hungary'],
        ['ID', 'Indonesia'],
        ['IE', 'Ireland'],
        ['IL', 'Israel'],
        ['IM', 'Isle of Man'],
        ['IN', 'India'],
        ['IQ', 'Iraq'],
        ['IS', 'Iceland'],
        ['IT', 'Italy'],
        ['JE', 'Jersey'],
        ['JM', 'Jamaica'],
        ['JO', 'Jordan'],
        ['JP', 'Japan'],
        ['KE', 'Kenya'],
        ['KG', 'Kyrgyzstan'],
        ['KH', 'Cambodia'],
        ['KI', 'Kiribati'],
        ['KM', 'Comoros'],
        ['KR', 'South Korea'],
        ['KW', 'Kuwait'],
        ['KY', 'Cayman Islands'],
        ['KZ', 'Kazakhstan'],
        ['LA', 'Laos'],
        ['LB', 'Lebanon'],
        ['LK', 'Sri Lanka'],
        ['LR', 'Liberia'],
        ['LS', 'Lesotho'],
        ['LY', 'Libya'],
        ['MA', 'Morocco'],
        ['MD', 'Moldova'],
        ['MG', 'Madagascar'],
        ['MK', 'North Macedonia'],
        ['MM', 'Myanmar'],
        ['MN', 'Mongolia'],
        ['MO', 'Macau'],
        ['MR', 'Mauritania'],
        ['MU', 'Mauritius'],
        ['MV', 'Maldives'],
        ['MW', 'Malawi'],
        ['MX', 'Mexico'],
        ['MY', 'Malaysia'],
        ['MZ', 'Mozambique'],
        ['NA', 'Namibia'],
        ['NG', 'Nigeria'],
        ['NI', 'Nicaragua'],
        ['NL', 'Netherlands'],
        ['NO', 'Norway'],
        ['NP', 'Nepal'],
        ['NZ', 'New Zealand'],
        ['OM', 'Oman'],
        ['PA', 'Panama'],
        ['PE', 'Peru'],
        ['PG', 'Papua New Guinea'],
        ['PH', 'Philippines'],
        ['PK', 'Pakistan'],
        ['PL', 'Poland'],
        ['PT', 'Portugal'],
        ['PY', 'Paraguay'],
        ['QA', 'Qatar'],
        ['RO', 'Romania'],
        ['RS', 'Serbia'],
        ['RU', 'Russia'],
        ['RW', 'Rwanda'],
        ['SA', 'Saudi Arabia'],
        ['SB', 'Solomon Islands'],
        ['SC', 'Seychelles'],
        ['SD', 'Sudan'],
        ['SE', 'Sweden'],
        ['SG', 'Singapore'],
        ['SH', 'Saint Helena'],
        ['SL', 'Sierra Leone'],
        ['SO', 'Somalia'],
        ['SR', 'Suriname'],
        ['SS', 'South Sudan'],
        ['ST', 'Sao Tome and Principe'],
        ['SY', 'Syria'],
        ['SZ', 'Eswatini'],
        ['TH', 'Thailand'],
        ['TJ', 'Tajikistan'],
        ['TM', 'Turkmenistan'],
        ['TN', 'Tunisia'],
        ['TO', 'Tonga'],
        ['TR', 'Turkey'],
        ['TT', 'Trinidad and Tobago'],
        ['TV', 'Tuvalu'],
        ['TW', 'Taiwan'],
        ['TZ', 'Tanzania'],
        ['UA', 'Ukraine'],
        ['UG', 'Uganda'],
        ['US', 'United States'],
        ['UY', 'Uruguay'],
        ['UZ', 'Uzbekistan'],
        ['VE', 'Venezuela'],
        ['VN', 'Vietnam'],
        ['VU', 'Vanuatu'],
        ['WS', 'Samoa'],
        ['YE', 'Yemen'],
        ['ZA', 'South Africa'],
        ['ZM', 'Zambia'],
        ['ZW', 'Zimbabwe'],
    ],

    'currencies' => [
        ['AED', 'UAE Dirham', 2, 'United Arab Emirates'],
        ['AFN', 'Afghan Afghani', 2, 'Afghanistan'],
        ['ALL', 'Albanian Lek', 2, 'Albania'],
        ['AMD', 'Armenian Dram', 2, 'Armenia'],
        ['ANG', 'Netherlands Antillian Guilder', 2, 'Netherlands Antilles'],
        ['AOA', 'Angolan Kwanza', 2, 'Angola'],
        ['ARS', 'Argentine Peso', 2, 'Argentina'],
        ['AUD', 'Australian Dollar', 2, 'Australia'],
        ['AWG', 'Aruban Florin', 2, 'Aruba'],
        ['AZN', 'Azerbaijani Manat', 2, 'Azerbaijan'],
        ['BAM', 'Bosnia and Herzegovina Mark', 2, 'Bosnia and Herzegovina'],
        ['BBD', 'Barbados Dollar', 2, 'Barbados'],
        ['BDT', 'Bangladeshi Taka', 2, 'Bangladesh'],
        ['BGN', 'Bulgarian Lev', 2, 'Bulgaria'],
        ['BHD', 'Bahraini Dinar', 3, 'Bahrain'],
        ['BIF', 'Burundian Franc', 0, 'Burundi'],
        ['BMD', 'Bermudian Dollar', 2, 'Bermuda'],
        ['BND', 'Brunei Dollar', 2, 'Brunei'],
        ['BOB', 'Bolivian Boliviano', 2, 'Bolivia'],
        ['BRL', 'Brazilian Real', 2, 'Brazil'],
        ['BSD', 'Bahamian Dollar', 2, 'Bahamas'],
        ['BTN', 'Bhutanese Ngultrum', 2, 'Bhutan'],
        ['BWP', 'Botswana Pula', 2, 'Botswana'],
        ['BYN', 'Belarusian Ruble', 2, 'Belarus'],
        ['BZD', 'Belize Dollar', 2, 'Belize'],
        ['CAD', 'Canadian Dollar', 2, 'Canada'],
        ['CDF', 'Congolese Franc', 2, 'Democratic Republic of the Congo'],
        ['CHF', 'Swiss Franc', 2, 'Switzerland'],
        ['CLF', 'Chilean Unidad de Fomento', 4, 'Chile'],
        ['CLP', 'Chilean Peso', 0, 'Chile'],
        ['CNH', 'Offshore Chinese Renminbi', 2, 'China'],
        ['CNY', 'Chinese Renminbi', 2, 'China'],
        ['COP', 'Colombian Peso', 2, 'Colombia'],
        ['CRC', 'Costa Rican Colon', 2, 'Costa Rica'],
        ['CUP', 'Cuban Peso', 2, 'Cuba'],
        ['CVE', 'Cape Verdean Escudo', 2, 'Cape Verde'],
        ['CZK', 'Czech Koruna', 2, 'Czech Republic'],
        ['DJF', 'Djiboutian Franc', 0, 'Djibouti'],
        ['DKK', 'Danish Krone', 2, 'Denmark'],
        ['DOP', 'Dominican Peso', 2, 'Dominican Republic'],
        ['DZD', 'Algerian Dinar', 2, 'Algeria'],
        ['EGP', 'Egyptian Pound', 2, 'Egypt'],
        ['ERN', 'Eritrean Nakfa', 2, 'Eritrea'],
        ['ETB', 'Ethiopian Birr', 2, 'Ethiopia'],
        ['EUR', 'Euro', 2, 'European Union'],
        ['FJD', 'Fiji Dollar', 2, 'Fiji'],
        ['FKP', 'Falkland Islands Pound', 2, 'Falkland Islands'],
        ['FOK', 'Faroese Krona', 2, 'Faroe Islands'],
        ['GBP', 'Pound Sterling', 2, 'United Kingdom'],
        ['GEL', 'Georgian Lari', 2, 'Georgia'],
        ['GGP', 'Guernsey Pound', 2, 'Guernsey'],
        ['GHS', 'Ghanaian Cedi', 2, 'Ghana'],
        ['GIP', 'Gibraltar Pound', 2, 'Gibraltar'],
        ['GMD', 'Gambian Dalasi', 2, 'The Gambia'],
        ['GNF', 'Guinean Franc', 0, 'Guinea'],
        ['GTQ', 'Guatemalan Quetzal', 2, 'Guatemala'],
        ['GYD', 'Guyanese Dollar', 2, 'Guyana'],
        ['HKD', 'Hong Kong Dollar', 2, 'Hong Kong'],
        ['HNL', 'Honduran Lempira', 2, 'Honduras'],
        ['HRK', 'Croatian Kuna', 2, 'Croatia'],
        ['HTG', 'Haitian Gourde', 2, 'Haiti'],
        ['HUF', 'Hungarian Forint', 2, 'Hungary'],
        ['IDR', 'Indonesian Rupiah', 2, 'Indonesia'],
        ['ILS', 'Israeli New Shekel', 2, 'Israel'],
        ['IMP', 'Manx Pound', 2, 'Isle of Man'],
        ['INR', 'Indian Rupee', 2, 'India'],
        ['IQD', 'Iraqi Dinar', 3, 'Iraq'],
        ['ISK', 'Icelandic Krona', 0, 'Iceland'],
        ['JEP', 'Jersey Pound', 2, 'Jersey'],
        ['JMD', 'Jamaican Dollar', 2, 'Jamaica'],
        ['JOD', 'Jordanian Dinar', 3, 'Jordan'],
        ['JPY', 'Japanese Yen', 0, 'Japan'],
        ['KES', 'Kenyan Shilling', 2, 'Kenya'],
        ['KGS', 'Kyrgyzstani Som', 2, 'Kyrgyzstan'],
        ['KHR', 'Cambodian Riel', 2, 'Cambodia'],
        ['KID', 'Kiribati Dollar', 2, 'Kiribati'],
        ['KMF', 'Comorian Franc', 0, 'Comoros'],
        ['KRW', 'South Korean Won', 0, 'South Korea'],
        ['KWD', 'Kuwaiti Dinar', 3, 'Kuwait'],
        ['KYD', 'Cayman Islands Dollar', 2, 'Cayman Islands'],
        ['KZT', 'Kazakhstani Tenge', 2, 'Kazakhstan'],
        ['LAK', 'Lao Kip', 2, 'Laos'],
        ['LBP', 'Lebanese Pound', 2, 'Lebanon'],
        ['LKR', 'Sri Lanka Rupee', 2, 'Sri Lanka'],
        ['LRD', 'Liberian Dollar', 2, 'Liberia'],
        ['LSL', 'Lesotho Loti', 2, 'Lesotho'],
        ['LYD', 'Libyan Dinar', 3, 'Libya'],
        ['MAD', 'Moroccan Dirham', 2, 'Morocco'],
        ['MDL', 'Moldovan Leu', 2, 'Moldova'],
        ['MGA', 'Malagasy Ariary', 2, 'Madagascar'],
        ['MKD', 'Macedonian Denar', 2, 'North Macedonia'],
        ['MMK', 'Burmese Kyat', 2, 'Myanmar'],
        ['MNT', 'Mongolian Togrog', 2, 'Mongolia'],
        ['MOP', 'Macanese Pataca', 2, 'Macau'],
        ['MRU', 'Mauritanian Ouguiya', 2, 'Mauritania'],
        ['MUR', 'Mauritian Rupee', 2, 'Mauritius'],
        ['MVR', 'Maldivian Rufiyaa', 2, 'Maldives'],
        ['MWK', 'Malawian Kwacha', 2, 'Malawi'],
        ['MXN', 'Mexican Peso', 2, 'Mexico'],
        ['MYR', 'Malaysian Ringgit', 2, 'Malaysia'],
        ['MZN', 'Mozambican Metical', 2, 'Mozambique'],
        ['NAD', 'Namibian Dollar', 2, 'Namibia'],
        ['NGN', 'Nigerian Naira', 2, 'Nigeria'],
        ['NIO', 'Nicaraguan Cordoba', 2, 'Nicaragua'],
        ['NOK', 'Norwegian Krone', 2, 'Norway'],
        ['NPR', 'Nepalese Rupee', 2, 'Nepal'],
        ['NZD', 'New Zealand Dollar', 2, 'New Zealand'],
        ['OMR', 'Omani Rial', 3, 'Oman'],
        ['PAB', 'Panamanian Balboa', 2, 'Panama'],
        ['PEN', 'Peruvian Sol', 2, 'Peru'],
        ['PGK', 'Papua New Guinean Kina', 2, 'Papua New Guinea'],
        ['PHP', 'Philippine Peso', 2, 'Philippines'],
        ['PKR', 'Pakistani Rupee', 2, 'Pakistan'],
        ['PLN', 'Polish Zloty', 2, 'Poland'],
        ['PYG', 'Paraguayan Guarani', 0, 'Paraguay'],
        ['QAR', 'Qatari Riyal', 2, 'Qatar'],
        ['RON', 'Romanian Leu', 2, 'Romania'],
        ['RSD', 'Serbian Dinar', 2, 'Serbia'],
        ['RUB', 'Russian Ruble', 2, 'Russia'],
        ['RWF', 'Rwandan Franc', 0, 'Rwanda'],
        ['SAR', 'Saudi Riyal', 2, 'Saudi Arabia'],
        ['SBD', 'Solomon Islands Dollar', 2, 'Solomon Islands'],
        ['SCR', 'Seychellois Rupee', 2, 'Seychelles'],
        ['SDG', 'Sudanese Pound', 2, 'Sudan'],
        ['SEK', 'Swedish Krona', 2, 'Sweden'],
        ['SGD', 'Singapore Dollar', 2, 'Singapore'],
        ['SHP', 'Saint Helena Pound', 2, 'Saint Helena'],
        ['SLE', 'Sierra Leonean Leone', 2, 'Sierra Leone'],
        ['SOS', 'Somali Shilling', 2, 'Somalia'],
        ['SRD', 'Surinamese Dollar', 2, 'Suriname'],
        ['SSP', 'South Sudanese Pound', 2, 'South Sudan'],
        ['STN', 'Sao Tome and Principe Dobra', 2, 'Sao Tome and Principe'],
        ['SYP', 'Syrian Pound', 2, 'Syria'],
        ['SZL', 'Eswatini Lilangeni', 2, 'Eswatini'],
        ['THB', 'Thai Baht', 2, 'Thailand'],
        ['TJS', 'Tajikistani Somoni', 2, 'Tajikistan'],
        ['TMT', 'Turkmenistan Manat', 2, 'Turkmenistan'],
        ['TND', 'Tunisian Dinar', 3, 'Tunisia'],
        ['TOP', 'Tongan Paanga', 2, 'Tonga'],
        ['TRY', 'Turkish Lira', 2, 'Turkey'],
        ['TTD', 'Trinidad and Tobago Dollar', 2, 'Trinidad and Tobago'],
        ['TVD', 'Tuvaluan Dollar', 2, 'Tuvalu'],
        ['TWD', 'New Taiwan Dollar', 2, 'Taiwan'],
        ['TZS', 'Tanzanian Shilling', 2, 'Tanzania'],
        ['UAH', 'Ukrainian Hryvnia', 2, 'Ukraine'],
        ['UGX', 'Ugandan Shilling', 0, 'Uganda'],
        ['USD', 'United States Dollar', 2, 'United States'],
        ['UYU', 'Uruguayan Peso', 2, 'Uruguay'],
        ['UZS', 'Uzbekistani Som', 2, 'Uzbekistan'],
        ['VES', 'Venezuelan Bolivar Soberano', 2, 'Venezuela'],
        ['VND', 'Vietnamese Dong', 0, 'Vietnam'],
        ['VUV', 'Vanuatu Vatu', 0, 'Vanuatu'],
        ['WST', 'Samoan Tala', 2, 'Samoa'],
        ['XAF', 'Central African CFA Franc', 0, 'CEMAC'],
        ['XCD', 'East Caribbean Dollar', 2, 'Organisation of Eastern Caribbean States'],
        ['XDR', 'Special Drawing Rights', 2, 'International Monetary Fund'],
        ['XOF', 'West African CFA franc', 0, 'CFA'],
        ['XPF', 'CFP Franc', 0, 'Collectivites d\'Outre-Mer'],
        ['YER', 'Yemeni Rial', 2, 'Yemen'],
        ['ZAR', 'South African Rand', 2, 'South Africa'],
        ['ZMW', 'Zambian Kwacha', 2, 'Zambia'],
        ['ZWL', 'Zimbabwean Dollar', 2, 'Zimbabwe'],
    ],

    'currency_exponents' => [
        'BHD' => 3,
        'BIF' => 0,
        'CLF' => 4,
        'CLP' => 0,
        'DJF' => 0,
        'GNF' => 0,
        'IQD' => 3,
        'ISK' => 0,
        'JOD' => 3,
        'JPY' => 0,
        'KMF' => 0,
        'KRW' => 0,
        'KWD' => 3,
        'LYD' => 3,
        'OMR' => 3,
        'PYG' => 0,
        'RWF' => 0,
        'TND' => 3,
        'UGX' => 0,
        'VND' => 0,
        'VUV' => 0,
        'XAF' => 0,
        'XOF' => 0,
        'XPF' => 0,
    ],
];
